#!/bin/bash

# Make all scripts executable
chmod +x *.sh

echo "🔧 All deployment scripts are now executable!"
echo ""
echo "📋 Available Scripts:"
echo "===================="
echo ""
echo "🚀 Main Setup:"
echo "  ./setup-vps.sh           - Initial VPS setup (run first)"
echo "  ./quick-deploy.sh         - Quick deployment of application"
echo "  ./update.sh              - Update application to latest version"
echo ""
echo "⚙️ Configuration:"
echo "  ./setup-cron.sh          - Setup automated monitoring and backup"
echo "  nginx.conf               - Nginx configuration template"
echo "  whatsapp-gateway.service - Systemd service configuration"
echo "  .env.production          - Production environment template"
echo ""
echo "🔧 Maintenance:"
echo "  ./backup.sh [type]       - Create backups (full/sessions/logs)"
echo "  ./health-check.sh        - Manual health check"
echo ""
echo "📖 Documentation:"
echo "  README.md                - Complete deployment guide"
echo ""
echo "🎯 Quick Start:"
echo "1. Upload to VPS: scp -r deploy/ user@your-server:~/"
echo "2. SSH to VPS: ssh user@your-server"
echo "3. Run setup: cd deploy && ./setup-vps.sh"
echo "4. Deploy app: ./quick-deploy.sh"
echo "5. Setup monitoring: ./setup-cron.sh"
echo ""
echo "✅ Ready for deployment!"
